### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by jayvdb** [aljungberg/pyle#2]
There are some test failures under Python 3.  Mostly str related changes, so it shouldnt be too difficult, but it does need to be manual as `futurize` and `modernize` make a bit of a mess of the conversion.

**Comment by aljungberg** [comment]
Added Python 3 support in b7a26e76 and b3f70260 for the v0.4 release.

**Comment by jayvdb** [comment]
Lovely .  Built at https://build.opensuse.org/package/show/home:jayvdb:py-new/python-pyle for Python 3.4, 3.6 and 3.7

v0.4 isnt on PyPI so I used the github archive.

`install_requires` shouldnt need to list argparse on Python 2.7+, as it already exists.  Or is the argparse shipped with Python not good enough?

The most urgent fix needed is `py_modules=['pyle', 'pyle_test'],` shouldnt include `'pyle_test'` , as it isnt a useful installed module.  To distribute that file in the sdist, it should be added to MANIFEST, which is already done.

Also the LICENSE and README.md should be included in the sdist, and the LICENSE included in the bdist_wheel.  https://github.com/justinmayer/django-autoslug/pull/56 is a reasonable PR to follow for those packaging improvements, or I can submit a PR if you like.

Also it would be nice if `python setup.py test` ran the tests, which should be just adding `test_suite='pyle_test'` in setup.py

**Comment by aljungberg** [comment]
Hmm I'm pretty sure the only reason `argparse` is there was for Python 2.6 compatibility. That's not necessary any more so I'll go ahead and remove it.

**Comment by aljungberg** [comment]
Fixed by 0c83bfae, 586a988b, 4573ac48, d11a7c92, b9401991 and d7565ad9. Also uploaded the final version to PyPi.

Thanks for the comments!
